import type { DefItem } from '@/components/ui'

export const DEFS: Record<string, DefItem[]> = {
  overview: [
    { term: 'Delivery Rate',       formula: 'Delivered ÷ Sent × 100',         desc: '% of sent messages successfully delivered to recipients.' },
    { term: 'Open Rate',           formula: 'Seen ÷ Delivered × 100',         desc: '% of delivered messages that were opened or seen.' },
    { term: 'CTR',                 formula: 'Clicks ÷ Delivered × 100',       desc: '% of delivered messages that received at least one click.' },
    { term: 'ROAS',                formula: 'Sales ÷ Cost',                   desc: 'Revenue generated per ₹1 spent on campaigns.' },
    { term: 'Buyer Conversion',    formula: 'Buyers ÷ Clicks × 100',          desc: '% of clickers who completed a purchase.' },
    { term: 'Revenue per Delivered', formula: 'Sales ÷ Delivered',            desc: 'Average ₹ revenue generated per delivered message.' },
  ],
  campaigns: [
    { term: 'Delivery Rate',       formula: 'Delivered ÷ Sent × 100',         desc: '% of sent messages successfully delivered.' },
    { term: 'Open Rate',           formula: 'Seen ÷ Delivered × 100',         desc: '% of delivered messages that were opened.' },
    { term: 'CTR',                 formula: 'Clicks ÷ Delivered × 100',       desc: '% of delivered messages that got a click.' },
    { term: 'Click to Open Rate',  formula: 'Clicks ÷ Seen × 100',            desc: 'Of messages seen, the % that also got a click.' },
    { term: 'Buyer Conversion',    formula: 'Buyers ÷ Clicks × 100',          desc: '% of clickers who completed a purchase.' },
    { term: 'Order Conversion',    formula: 'Orders ÷ Clicks × 100',          desc: '% of clickers who placed an order.' },
    { term: 'Revenue per Delivered', formula: 'Sales ÷ Delivered',            desc: 'Average ₹ revenue per delivered message.' },
    { term: 'Unsubscribe Rate',    formula: 'Unsubs ÷ Delivered × 100',       desc: '% of recipients who unsubscribed after delivery.' },
    { term: 'Buyer to Segment',    formula: 'Buyers ÷ Sent × 100',            desc: 'Buyers as % of total messages sent (segment size proxy).' },
    { term: 'Order to Segment',    formula: 'Orders ÷ Sent × 100',            desc: 'Orders as % of total messages sent.' },
    { term: 'ROAS',                formula: 'Sales ÷ Cost',                   desc: 'Revenue generated per ₹1 spent on this campaign.' },
  ],
  automations: [
    { term: 'Open Rate',           formula: 'Seen ÷ Delivered × 100',         desc: '% of delivered automation messages that were opened.' },
    { term: 'CTR',                 formula: 'Clicks ÷ Delivered × 100',       desc: 'Click rate on automation messages.' },
    { term: 'Buyer Conversion',    formula: 'Buyers ÷ Clicks × 100',          desc: '% of clickers who completed a purchase.' },
    { term: 'Revenue per Sent',    formula: 'Sales ÷ Sent',                   desc: 'Revenue generated per message sent.' },
    { term: 'Revenue per Delivered', formula: 'Sales ÷ Delivered',            desc: 'Revenue generated per message delivered.' },
    { term: 'ROAS',                formula: 'Sales (or Recovery) ÷ Cost',     desc: 'Revenue per ₹1 spent on this automation.' },
    { term: 'Recovery Rate',       formula: 'Recovered Carts ÷ Sent × 100',  desc: '(Cart Recovery) % of targeted carts that were recovered.' },
    { term: 'Cost per Recovery',   formula: 'Cost ÷ Recovered Carts',         desc: '(Cart Recovery) Average cost to recover one abandoned cart.' },
  ],
  segment: [
    { term: 'Avg Delivery Rate',   formula: 'Σ Delivered ÷ Σ Sent × 100',    desc: 'Aggregate delivery rate across all campaigns for this segment.' },
    { term: 'Avg Open Rate',       formula: 'Σ Seen ÷ Σ Delivered × 100',    desc: 'Aggregate open rate across all campaigns in this segment.' },
    { term: 'Segment ROAS',        formula: 'Σ Sales ÷ Σ Cost',              desc: 'Aggregate ROAS across all campaigns targeting this segment.' },
    { term: 'Revenue Efficiency',  formula: 'Σ Sales ÷ Σ Delivered',         desc: 'Revenue per delivered message across this entire segment.' },
    { term: 'Total Buyers',        formula: 'Σ Buyers across segment',        desc: 'Total distinct buyers attributed to this segment group.' },
  ],
  offer: [
    { term: 'Offer ROAS',          formula: 'Σ Sales ÷ Σ Cost',              desc: 'Aggregate ROAS across all campaigns using this offer type.' },
    { term: 'Revenue Efficiency',  formula: 'Σ Sales ÷ Σ Delivered',         desc: 'Revenue per delivered message for this offer type.' },
    { term: 'Avg CTR',             formula: 'Σ Clicks ÷ Σ Delivered × 100',  desc: 'Aggregate click rate for campaigns using this offer.' },
    { term: 'Buyer Conversion',    formula: 'Σ Buyers ÷ Σ Clicks × 100',     desc: 'Aggregate buyer conversion rate for this offer type.' },
  ],
  funnel: [
    { term: 'Delivery Rate',       formula: 'Delivered ÷ Sent × 100',        desc: '% of messages that reached recipients.' },
    { term: 'Open Rate',           formula: 'Seen ÷ Delivered × 100',        desc: '% of delivered messages that were opened.' },
    { term: 'Click Rate (sent)',   formula: 'Clicks ÷ Sent × 100',           desc: '% of all sent messages that generated a click.' },
    { term: 'Click to Open',       formula: 'Clicks ÷ Seen × 100',           desc: 'Of opened messages, the % that also generated a click.' },
    { term: 'Buyer Rate',          formula: 'Buyers ÷ Sent × 100',           desc: '% of all sent messages that led to a buyer.' },
    { term: 'Click to Purchase',   formula: 'Buyers ÷ Clicks × 100',         desc: '% of clicks that ultimately converted to a purchase.' },
  ],
  revenue: [
    { term: 'Revenue per Delivered', formula: 'Sales ÷ Delivered',           desc: 'Average revenue per delivered message.' },
    { term: 'Revenue per Sent',    formula: 'Sales ÷ Sent',                  desc: 'Average revenue per sent message (incl. undelivered).' },
    { term: 'Order Conversion',    formula: 'Orders ÷ Clicks × 100',         desc: '% of clicks that resulted in an order.' },
    { term: 'Buyer Conversion',    formula: 'Buyers ÷ Clicks × 100',         desc: '% of clicks that resulted in a buyer.' },
    { term: 'ROAS',                formula: 'Sales ÷ Cost',                  desc: 'Revenue per ₹1 of ad spend.' },
    { term: 'Cost per Buyer',      formula: 'Cost ÷ Buyers',                 desc: 'Average acquisition cost per buyer.' },
    { term: 'Cost per Order',      formula: 'Cost ÷ Orders',                 desc: 'Average cost per order placed.' },
  ],
  historical: [
    { term: '7-Day Ingestion',     formula: 'Rolling 7-day window',          desc: 'Campaign trend and retention analysis over the last 7 days.' },
    { term: '1-Day Ingestion',     formula: 'Single day snapshot',           desc: 'Daily performance snapshot for campaign health monitoring.' },
    { term: 'Day-over-Day Change', formula: '(Today − Yesterday) ÷ Yesterday × 100', desc: 'Percentage change in a metric vs the previous day.' },
  ],
}
